spring:
  datasource:
    url: jdbc:sqlserver://mohit1.database.windows.net:1433;database=mohitdb1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: mohit
    password: Password@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


